Механизм удаления неиспользованных файлов
coder1coder/Hackathon pull request #317
Opened 2023-06-19 16:56 UTC by gorohov09

closes #313

2023-06-22 08:02 UTC, coder1coder requested changes

2023-06-22 08:02 UTC, coder1coder commented on Hackathon.Common/Models/FileStorage/StorageFile.cs
> +    /// Флаг - нужно ли удалять файл
"Файл удален"

2023-06-22 08:02 UTC, coder1coder commented on Hackathon.DAL/Entities/FileStorageEntity.cs
> +    /// <summary>
"Файл удален"

2023-06-25 08:16 UTC, coder1coder commented on Hackathon.BL/Event/EventService.cs
> +        }
Весь кусок по снятию флага IsDeleted фотографии мероприятия вынести в отдельный приватный метод класса, который можно будет также использовать и для метода обновления мероприятия. Использовать его  как при создании, так и при обновлении. Метод вызывать ПОСЛЕ методов сохранения и обновления в репозиториях.

2023-06-25 08:20 UTC, coder1coder commented on Hackathon.UI/src/app/components/event/cards/event-create-edit-card/event-create-edit-card.component.ts
>          }
Использовать ErrorProcessor, по необходимости дополнить его метод, новыми условиями

![image](https://github.com/coder1coder/Hackathon/assets/13835906/da92e650-4139-4e29-9a15-a3148fbef50a)

2023-06-25 08:21 UTC, coder1coder commented on Hackathon.Common/JobsConstants.cs
> +    public static int UnusedFilesDeleteJobFrequency = 24;
В конфиге 48 по умолчанию, тут 24, нужно единообразие

2023-06-25 08:22 UTC, coder1coder commented on Hackathon.Common/Configuration/FileSettings.cs
> +    public int UnusedFilesDeleteJobFrequencyInHours { get; set; } = 24;
В конфигах указано 48, тут 24, непонятно откуда расхождение, сделать одинаково

2023-06-25 08:25 UTC, coder1coder commented on Hackathon.DAL/Repositories/FileStorageRepository.cs
> +    }
Переделать метод/интерфейс и джобу под вот такую реализацию

```
public Task<long[]> GetIsDeletedFilesAsync()
=> _dbContext.StorageFiles
.Where(x => x.IsDeleted == true)
.Select(x=>x.Id)
.ToArrayAsync();
```

2023-06-25 22:24 UTC, gorohov09 commented on Hackathon.BL/Event/EventService.cs
> +        }
А почему метод вызывать после методов сохранения и обновления в репозиториях? Может быть такая ситуация: При создании мероприятия картинка по ImageId не найдена, точнее была удалена джобой и мы все равно этот ImageId сохраним до этой проверки. И получится, что фронт будет тащить картинку по этому id. Лишние запросы + будут валится ошибки в консоли. Предлагаю сохранять после этого метода. Если картинка не найдена, мы можем в ImageId = null сохранить и тогда будет эффективнее. Аналогично с обновлениями.

2023-06-26 12:28 UTC, coder1coder commented on Hackathon.BL/Event/EventService.cs
> +        await _fileStorageRepository.UpdateFlagIsDeleted(uploadResult.Id, true);
для пользователя сделать по аналогии

2023-06-26 12:48 UTC, coder1coder commented on Hackathon.BL/Event/EventService.cs
>          return Result<long>.FromValue(eventId);
При создании мероприятия сделай так:
```
await AssignImageIdFromTemporaryFile(eventCreateParameters);

var eventId = await _eventRepository.CreateAsync(eventCreateParameters);
      await _messageBus.Publish(new EventLogModel(
          EventLogType.Created,
          $"Создано новое событие с идентификатором '{eventId}'",
          eventCreateParameters.OwnerId
      ));

return Result<long>.FromValue(eventId);
```
Приватный метод так:
```
private Task AssignImageIdFromTemporaryFile(EventCreateParameters parameters)
{

if (!parameters.ImageId.HasValue)
return;

StorageFile file = null;

try
{

file = await _fileStorageRepository.GetAsync(fileId.Value);

if (file is not null)
{
         //Снимаем ранее установленный флаг, чтобы не удалить фотографию события
         await _fileStorageRepository.UpdateFlagIsDeleted(fileModel.Id, false);
}

} catch (Exception ex) { //залогировать }
finally
{
  parameters.ImageId = file?.Id
}
```

Обновление по аналогии

2023-06-26 12:49 UTC, coder1coder commented on Hackathon.BL/Event/EventService.cs
> +    }
вернуть обратно в метод создания

2023-06-26 14:17 UTC, coder1coder approved these changes

2023-06-26 14:18 UTC, merged