фикс изменения ссылки на гх реп
coder1coder/Hackathon pull request #385
Opened 2023-10-29 10:33 UTC by Proger0014

2023-10-29 10:55 UTC, coder1coder commented on Hackathon.Common/RegexPatterns.cs
> +    public const string GithubBranchLink = @"(https://github.com/)([0-9a-zA-Z-_]+)/([0-9a-zA-Z-_]+)/tree/([0-9a-zA-Z-_]+)";
![image](https://github.com/coder1coder/Hackathon/assets/13835906/2e28f95f-e107-4929-855e-8b8405c4005c)

Переделанный регекс не проходит все кейсы. Необходимо поправить, написать тесты.

2023-10-29 14:16 UTC, coder1coder requested changes

2023-10-29 14:16 UTC, coder1coder commented on Hackathon.BL.Tests.Common/Project/TestDataCollections/ProjectServiceTestDataCollections.cs
> +    public static IEnumerable<object[]> ValidateSuiteUnvalidBranchLinksInit()
это можно упростить вернув сразу заранее определенную коллекцию

2023-10-29 14:16 UTC, coder1coder commented on Hackathon.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Hackathon.BL.Tests.Common", "Hackathon.BL.Tests.Common\Hackathon.BL.Tests.Common.csproj", "{A60D1847-D0DF-40B8-A993-FE121AF68670}"
Нет необходимости в отдельной сборке, эти классы можно и нужно разместить в сборке тестов

2023-11-04 12:55 UTC, coder1coder commented on Hackathon.Tests/Hackathon.BL.Tests/Project/DataCollections.cs
> +    }
Какой смысл от такого набора тестовых данных если меняется только ссылка?
Может стоит исключить UpdateProjectFromGitBranchParameters и оставить ссылку?
Ну и конструкцию можно упростить, зачем создавать массив по которому потом в форыче проходить и возвращать список?

2023-11-04 12:55 UTC, coder1coder commented on Hackathon.Tests/Hackathon.BL.Tests/Project/DataCollections.cs
> +}
Какой смысл от такого набора тестовых данных если меняется только ссылка?
Может стоит исключить UpdateProjectFromGitBranchParameters и оставить ссылку?
Ну и конструкцию можно упростить, зачем создавать массив по которому потом в форыче проходить и возвращать список?

2023-11-04 12:57 UTC, coder1coder commented on Hackathon.Tests/Hackathon.BL.Tests/Project/Helpers.cs
> +}
исключить, не вижу проблемы создать валидатор там где он используется

2023-11-04 12:57 UTC, coder1coder commented on Hackathon.Tests/Hackathon.BL.Tests/Project/Helpers.cs
> +}
в тестах это можно сделать в конструкторе 1 раз

2023-11-11 11:10 UTC, Proger0014 commented on Hackathon.Tests/Hackathon.BL.Tests/Project/Helpers.cs
> +}
хм, а здесь советуют вспомогательные методы использовать: https://learn.microsoft.com/ru-ru/dotnet/core/testing/unit-testing-best-practices#prefer-helper-methods-to-setup-and-teardown

2023-11-11 12:12 UTC, merged