#408 - Отображать количество проставленных реакций в профиле пользователя
coder1coder/Hackathon pull request #411
Opened 2023-11-19 10:43 UTC by gorohov09

closes #408

2023-11-19 17:43 UTC, coder1coder commented on Hackathon.DAL/Repositories/UserProfileReactionRepository.cs
> +        await _dbContext.UserReactions
можно убарть async/await, в условии исключить записи с Reaction = 0

2023-11-20 18:58 UTC, AshtonBro commented on Hackathon.UI/src/app/models/User/UserProfileReaction.ts
> +export class UserProfileReactionModel {
Перепиши на export interface IUserProfileReaction

2023-11-20 18:58 UTC, AshtonBro commented on Hackathon.UI/src/app/models/User/UserProfileReaction.ts
> +}
без underfined

2023-11-20 20:44 UTC, coder1coder requested changes

2023-11-20 20:44 UTC, coder1coder commented on Hackathon.BL/User/UserProfileReactionService.cs
> +    public async Task<List<UserProfileReactionModel>> GetReactionsByTypeAsync(long targetUserId)
В качестве возвращаемого результата метода сервиса надо сделать Result<T>

2023-11-20 20:44 UTC, coder1coder commented on Hackathon.Common/Models/User/UserProfileReactionModel.cs
> +}
summary

2023-11-20 20:44 UTC, coder1coder commented on Hackathon.DAL/Repositories/UserProfileReactionRepository.cs
> +            .Where(x => x.TargetUserId == targetUserId && x.Reaction != 0)
в Enum реакций добавить 0 как None или Default и указать его здесь, чтобы не был магических чисел

2023-11-20 20:44 UTC, coder1coder commented on Hackathon.UI/src/app/components/profile/view/profile.view.component.scss
> +  .reaction-pointer  {
использовать псевдоэлемент :hover

2023-11-20 20:44 UTC, coder1coder commented on Hackathon.BL/User/UserProfileReactionService.cs
>  }
добавить TODO на оптимизацию, есть подозрения что это можно сделать более универсально, не хочется каждый раз возвращаться сюда при добавлении новой реакции

2023-11-22 17:30 UTC, AshtonBro approved these changes

2023-11-22 18:01 UTC, coder1coder approved these changes

2023-11-22 18:04 UTC, merged